#define MAX 6
#define MIN 1
#define NOMBRE_DOUBLE 3
#define NOMBRE_MAX 50
#define NOMBRE_MAISON 32
#define NOMBRE_HOTEL 12
#define NOMBRE_PROPRIETE 16
#define NOMBRE_CASE 32
#define TAILLE_NOM_MAX 50
#define NB_CARTESCHANCE_MAX 10
#define NOMBRE_GROUPES 8
#ifndef MONOPOLY_MACRO_H
#define MONOPOLY_MACRO_H

#endif //MONOPOLY_MACRO_H
