#define MAX 6
#define MIN 1
#define NOMBRE_DOUBLE 3
#define NOMBRE_MAX 50
#define NOMBRE_MAISON 32
#define NOMBRE_HOTEL 12
#define NOMBRE_PROPRIETE 16
#define NOMBRE_CASE 32
#define TAILLE_NOM_MAX 50
#define NB_CARTE 10
